require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'
install! 'cocoapods', :deterministic_uuids => false

use_frameworks! :linkage => :static
# Облегченная библиотека, содержит только карту, слой пробок, 
# LocationManager, UserLocationLayer и возможность скачивать офлайн-карты (только в платной версии).
pod 'YandexMapsMobile', '4.2.2-full'

$RNFirebaseAsStaticFramework = true

target 'vizitka' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNYamap', :path => '../node_modules/react-native-yamap'

  pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'

  pod 'react-native-biometrics', :path => '../node_modules/react-native-biometrics'

  pod 'react-native-restart', :path => '../node_modules/react-native-restart'

  pod 'Firebase', :modular_headers => true
  
  pod 'FirebaseCoreInternal', :modular_headers => true
  
  pod 'GoogleUtilities', :modular_headers => true

  pod 'FirebaseCore', :modular_headers => true

  target 'vizitkaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  # post_install do |installer|
  #   installer.pods_project.build_configurations.each do |config|
  #     config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  #   end
end
